### ISSUE TITLE
the batch in dataloader has no key 'size_org'

### ISSUE THREAD

**Issue by tjut311** [coreeey/OCT2Former#1]
File "train.py", line 229, in test
    org_size = batch["size_org"]
KeyError: 'size_org'

**Comment by coreeey** [comment]
'size_org' is used to restore the original size of the input image, which is the same as the 'crop_size' in dataset. You can refer to our newly updated code, which has removed some redundant parts.

**Comment by coreeey** [comment]
> 'size_org' is used to restore the original size of the input image, which is the same as the 'crop_size' in dataset. You can refer to our newly updated code, which has removed some redundant parts.

'size_org' is used to restore the original size of the input image, which is the same as the 'crop_size' in dataset. You can refer to our newly updated code, which has removed some redundant parts.
